/*
Version No   Version Description
----------   -------------------
v0.0.19       Adding keywords for FM 2 DT
*/

-- CREATING THE JOURNEY
INSERT INTO journeys (journey_id,journey_name,published)
	VALUES ('25378708-08d7-4192-8e4d-68ceb5013c9c'::uuid,'FM 2',true);
-----------------------

-- CREATING FRESH TABLE
drop table if exists temp_domain_values; 
create table temp_domain_values (search_term varchar(75),
				 domain_name varchar(50),
				 domain_desc varchar(2000));

drop table if exists temp_journeys;
create table temp_journeys (domain_name varchar(50),
						    journey_uuid uuid);
-----------------------


-- INSERTING NEW KEYWORDS 
INSERT INTO temp_journeys values ('FM 2','25378708-08d7-4192-8e4d-68ceb5013c9c');

insert into temp_domain_values values
('Defence Housing','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Defence Accommodation','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Defence Housing Management','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Defence FM','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Firing Range','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Range','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('TAROM','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Warfare','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Training Area','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Military','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Rural Estate Maintenance','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Land Management','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Safe Place to Train','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Targets','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Targetry','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('MOD','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('MOD Terms','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Defstan (or Defence Standard)','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Establishment','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('anatomical','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('anti-bacterial','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('anti-viral','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Barrier Mat','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('bins','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('buffing','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('caretaking','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('carpet','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('changing room','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Chemical','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Chimney','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('clean','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('cleaner','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('clearance','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('clinical','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('conference centre','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('court','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('crime scene cleaning','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('decontaminate','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('dirty','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('dusting','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('floor cleaning','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('fogging','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('fume cupboard','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Graffiti','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('gutter','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('h2o2','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('hazardous waste','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('health centre','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('high level','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('hospital','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('hydrogen peroxide','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('infection control','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('internal','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('janitor','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Lab','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Litter','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('litter picking','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('misting','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('mobile cleaner','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('mobile cleaning','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Offensive','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Oven','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('periodic','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('polishing','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('porter','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('pressure washing','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('re-sealing','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('sandblast','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('sanitisation','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('sanitise','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Sharps','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('soft fm','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('special needs','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('sweepers','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('touchpoint','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('trauma','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('vacuum cleaners','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('visitor centre','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('wetroom','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('window','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('access control','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('adaptations','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('archiving','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('automatic access control systems','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('barriers','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('billable','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('biometric technologies','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cable','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cable management','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('car park management','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cash','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cash and valuables in transit','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('clean','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('communal','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('curtains','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('decent homes standards 2006','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('deep','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('delivery plan','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('design','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('detection','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('detector','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('digital video recorders (DVR)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('dog','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('doors','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('electronic airspace','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('electronic locking systems','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('engineering','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('environmental','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fence','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fire','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fire alarm','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('flag flying','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('flowers','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('gate','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('hard','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('hazardous waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('helpdesk','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('hoist','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('homes england','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing and planning act 2016','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing associations','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing co-operatives housing trusts','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing infrastructure','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('install','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('internal','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('intruder detection systems (IDS)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('lamping','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('local authority housing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('local housing companies','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('locking','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('maintenance','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('management','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('manned','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('mats','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('modelling','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('monitoring','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('network video recorders (NVR)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('open up','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('passes','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('perimeter intrusion detection systems (PIDS)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('periodic','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('planned','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('porter','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('private registered providers (prps)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('public sector housing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('radon','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('re-lamping','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('reception service','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('recreational facilities','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('rental','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('reservoir','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('restaurant','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('risk','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('security assessments','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('security lighting','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('security management systems','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('security screening applications','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('signalling','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('snow','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('social housing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('soft','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('standby','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('statutory','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('stock management','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('supply','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('systems','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('taxi booking','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('tree','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('voice','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('voice announcement system','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('voltage','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('wall','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('walling system','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('window','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('x ray','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.');

insert into search_terms (search_term)
select  distinct lower(search_term)
from    temp_domain_values td;
-----------------------

-- MAPPING NEW KEYWORDS WITH GM LITE
insert into search_domains (search_id,journey_id,modifier_journey_name,journey_selection_text,journey_selection_description)
select distinct 
		st.search_id,
		CAST('c9dd4455-7d23-4822-9912-eab4da9fc5a2' AS uuid) as journey_id,
		'GM Lite' as modifier_journey_name,
		'Something else' as journey_selection_text,
		'What I need is not listed here' as journey_selection_description
from   search_terms st
join   temp_domain_values td on lower(td.search_term) = st.search_term;
------------------------------------

-- MAPPING OLD KEYWORDS WITH THE NEW JOURNEY
insert into temp_domain_values values
('Accommodation','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('Defence','Training Estate Services','Access to UK-wide facilities management (FM) services, tailored towards specific defence and training estate FM requirements.'),
('asbestos','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('building','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('call centre','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('car park','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('cleaning','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('clinical waste','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('college','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('Consumables','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('deep cleaning','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('external','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('facilities','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('fm','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('grounds','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('handyman','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('housekeeping','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('hygiene','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('key holding','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('kitchen','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('medical waste','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('nursery','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('office','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('porterage','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('reactive','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('routine','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('school','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('signage','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('specialist','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('university','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('waste','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('windows','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('workplace','Building Cleaning Services and Hazardous Waste','Building Cleaning Services and Hazardous Waste Includes contract cleaning services, and medical and hazardous waste services'),
('ac','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('access','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('accommodation','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('air conditioning','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('alarm','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('appliance','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('asbestos','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('asset','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('av','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('bim','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('bin areas','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('blinds','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('blockers','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('bms','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('bollard','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('building','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('building information modelling','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cafm','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('canine','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('car park','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('carbon neutral homes','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('care homes','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('catering','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cctv','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('central government housing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('certification','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('christmas tree','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('classified waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('cleaning','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('clinical waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('clocks','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('community housing cymru (chc)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('condition','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('corridors','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('deep cleaning','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('deli-bar','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('disability','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('electrical','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('emergency','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('epc','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('equipment','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('external','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fabric','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('facilities','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fam','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('feminine hygiene waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fences and walls','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('flag','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('fm','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('food','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('foyers','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('garages','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('gardens','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('gas','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('general waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('grounds','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('guarding','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('handyman','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('high voltage','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('horticultural','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('hospitality','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housekeeping','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing maintenance','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing management','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing stock','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('housing units','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('hvac','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('hygiene','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('ice','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('inspection','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('intruder','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('key holding','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('kitchen','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('lamps','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('lift','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('lock up','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('locksmith','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('m&e','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('machine','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('mail','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('mechancial','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('medical waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('messenger','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('mobilisation','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('national housing federation','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('nvr','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('occupation','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('office','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('outsourcing playbook','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('panic','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('pat','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('pathways','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('patrols','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('perimeter','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('pest','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('physical','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('planting','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('plants','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('play areas','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('pond','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('portable','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('porterage','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('power','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('ppm','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('property','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('protection','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('prps','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('reactive','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('reactive repairs','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('reception','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('recycled waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('rent','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('repair maintenance and improvement','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('reprographics','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('response','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('river','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('rmi','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('roadways','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('room','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('routine','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('scanners','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('screening','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('security','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('servicing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('sfg20','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('signage','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('social value','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('soft landings','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('special need','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('specialist','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('stairs','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('statutory obligations','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('survey','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('switchgear','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('testing','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('the northern ireland federation of housing associations (nifha)','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('nifha','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('sfha','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('trolley','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('vacant','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('vending','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('ventilation','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('void','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('waste','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('water','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('water feature','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('windows','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.'),
('workplace','Workplace Services (FM Marketplace 2)','Security, housing and Facilities Management (FM) services for defence, central government and wider public sector.');

insert into search_domains (search_id,journey_id,modifier_journey_name,journey_selection_text,journey_selection_description)
select distinct st.search_id,
       CAST('25378708-08d7-4192-8e4d-68ceb5013c9c' AS uuid) as journey_id,
	   td.domain_name,
	   td.domain_name,
	   td.domain_desc
from   search_terms st
join   temp_domain_values td on lower(td.search_term) = st.search_term;
--------------------------------------------

INSERT INTO error_messages (error_message_code, error_summary, error_message)
VALUES
('ERR_GM055','Select the type of security service you need','Select the type of security service you need'),
('ERR_GM056','Select the sector you are burying for','Select the sector you are burying for'),
('ERR_GM057','Select if you need additional services','Select if you need additional services'),
('ERR_GM058','Select if you need housing management or housing maintenance and repair services','Select if you need housing management or housing maintenance and repair services');


INSERT INTO error_usage (failure_validation_type_code, error_message_code, question_id)
values
('noSelection','ERR_GM055','8e74ed26-62ca-4c74-9658-599369ea13b5'),
('noSelection','ERR_GM056','fba9ec9a-007c-422c-8237-2cd24ad0c85b'),
('noSelection','ERR_GM057','80753c8e-dad2-4fbd-82d2-1bc9d4f6876b'),
('noSelection','ERR_GM058','9b8b1f17-d5e7-42ee-99a1-46b703947296');
--------------------------------------------